version: "2"

run:
  tests: true

linters:
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          xml: snake
          bson: snake

  exclusions:
    rules:
      # Disable strict linters in test files
      - path: _test\.go
        linters:
          - funlen
          - dupl
          - goconst
          - mnd
          - wrapcheck
          - err113
          - gocognit
          - gosec

  default: none
  enable:
    # Core (must have)
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

    # Bug detection
    - bodyclose
    - nilerr
    - nilnesserr
    - nilnil
    - durationcheck
    - errchkjson
    - contextcheck
    - noctx
    - makezero
    - reassign
    - wastedassign
    - forcetypeassert
    - noinlineerr

    # Security
    - gosec

    # Code quality
    - gocognit
    - goconst
    - gocritic
    - unconvert
    - unparam
    - prealloc
    - perfsprint
    - usestdlibvars
    - intrange
    - copyloopvar
    - nestif
    - decorder
    - grouper
    - importas

    # Style
    - misspell
    - dupword
    - asciicheck
    - bidichk
    - whitespace
    - dogsled
    - nakedret
    - predeclared
    - errname
    - errorlint
    - funlen
    - lll
    - nonamedreturns
    - godot
    - tagliatelle
    - tagalign
    - nlreturn
    - wsl_v5

    # Strict error handling
    - err113
    - wrapcheck

    # Magic numbers
    - mnd

    # Testing
    - thelper
    - testpackage
    - testableexamples

    # Logging
    - sloglint

    # HTTP
    - canonicalheader

    # Observability
    - spancheck
    - promlinter

    # Lint hygiene
    - nolintlint

    # Other useful
    - asasalint
    - containedctx
    - fatcontext
    - mirror
    - nosprintfhostport
    - gomoddirectives
    - goprintffuncname
    - gocheckcompilerdirectives
    - gochecknoinits
    - exhaustive
    - interfacebloat
    - inamedparam
    - dupl
    - recvcheck
    - exptostd

formatters:
  enable:
    - gofumpt
    - goimports
