version: "2"

run:
  tests: true

  default: none
  enable:
    # Core (must have)
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

    # Bug detection
    - bodyclose
    - nilerr
    - nilnesserr
    - nilnil
    - durationcheck
    - errchkjson
    - contextcheck
    - noctx
    - makezero
    - reassign
    - wastedassign
    - forcetypeassert
    - noinlineerr

    # Security
    - gosec

    # Code quality
    - gocognit
    - goconst
    - gocritic
    - unconvert
    - unparam
    - prealloc
    - perfsprint
    - usestdlibvars
    - intrange
    - copyloopvar
    - nestif
    - decorder
    - grouper
    - importas

    # Style (strict)
    - misspell
    - dupword
    - asciicheck
    - bidichk
    - whitespace
    - dogsled
    - nakedret
    - predeclared
    - errname
    - errorlint
    - nlreturn
    - wsl_v5
    - funlen
    - lll
    - nonamedreturns
    - godot
    - tagliatelle
    - tagalign

    # Testing
    - thelper
    - testpackage
    - testableexamples

    # Other useful
    - asasalint
    - containedctx
    - fatcontext
    - mirror
    - nosprintfhostport
    - gomoddirectives
    - goprintffuncname
    - gocheckcompilerdirectives
    - gochecknoinits
    - exhaustive
    - interfacebloat
    - inamedparam
    - dupl
    - recvcheck
    - exptostd

formatters:
  enable:
    - gofumpt
    - goimports
